permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:

name: CI
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v3

      - name: Install stable
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - run: cargo +nightly fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  rust-tests:
    runs-on: ubuntu-latest
    name: rust tests
    steps:
      - uses: actions/checkout@v3

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: cargo test
        run: cargo test --all-features --all-targets

  node-tests:
    runs-on: ubuntu-latest
    name: node tests
    strategy:
      fail-fast: false
      matrix:
        node: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v3

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: yarn install
        run: yarn install --immutable

      - name: yarn test
        run: yarn test

  doc:
    runs-on: ubuntu-latest
    name: nightly / doc
    needs:
      - rust-tests
      - node-tests
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docs

      - name: Fix for GitHub Pages
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=neon_serde\">" > target/doc/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
